
<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\tModLoader.targets" />
  <PropertyGroup>
    <AssemblyName>OmoriMod</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="Systems\AbilitySystem\ItemAbilities\Actives\" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Tests\**\*.cs" />
  </ItemGroup>
</Project>